# IFID_STATE: eyJzb3VyY2VzIjpbeyJpZCI6ImMxMzg3NzhjLWZmZDEtNDc0Yy1hNGJhLWYxNTU4OGQwMzhhYiIsIm5hbWUiOiJtaWxrIiwidHlwZSI6ImRhaXJ5IiwiaXNfYWxsZXJnZW4iOnRydWUsImlzX2RlY2xhcmFibGUiOnRydWV9LHsiaWQiOiJhNmE3MTA1My1iYmEyLTRiZmMtOWZiYS02OGQwYTM4NGI2ZTAiLCJuYW1lIjoic3RyZXB0b2NvY2N1cyB0aGVybW9waGlsdXMiLCJ0eXBlIjoibWljcm9iaWFsIiwiaXNfYWxsZXJnZW4iOmZhbHNlLCJpc19kZWNsYXJhYmxlIjpmYWxzZX0seyJpZCI6ImIxNWU0MGUzLTM5NzItNGYxZC04Y2M4LTBlNzIwZDI5NmQxYiIsIm5hbWUiOiJsYWN0b2JhY2lsbHVzIGFjaWRvcGhpbHVzIiwidHlwZSI6Im1pY3JvYmlhbCIsImlzX2FsbGVyZ2VuIjpmYWxzZSwiaXNfZGVjbGFyYWJsZSI6ZmFsc2V9LHsiaWQiOiI2M2ZlNDUyNS05OWM5LTRkNGQtOGM5ZC0wYjEzMDI3ZDZkZWEiLCJuYW1lIjoibGFjdG9iYWNpbGx1cyBkZWxicnVlY2tpaSBzdWJzcC4gYnVsZ2FyaWN1cyIsInR5cGUiOiJtaWNyb2JpYWwiLCJpc19hbGxlcmdlbiI6ZmFsc2UsImlzX2RlY2xhcmFibGUiOmZhbHNlfSx7ImlkIjoiYTJlMmY3NDgtMDA1OS00ZWU3LWJlZjYtNmM1MjBiMmM2MzdjIiwibmFtZSI6ImxpbW9zaWxhY3RvYmFjaWxsdXMgcmV1dGVyaSIsInR5cGUiOiJtaWNyb2JpYWwiLCJpc19hbGxlcmdlbiI6ZmFsc2UsImlzX2RlY2xhcmFibGUiOmZhbHNlfSx7ImlkIjoiYTZlZjdlYTMtNTIxNy00ZmI5LTg2YjMtMDhjNjY3NWEwZmZjIiwibmFtZSI6ImJpZmlkb2JhY3Rlcml1bSBhbmltYWxpcyBzdWJzcC4gbGFjdGlzIiwidHlwZSI6Im1pY3JvYmlhbCIsImlzX2FsbGVyZ2VuIjpmYWxzZSwiaXNfZGVjbGFyYWJsZSI6ZmFsc2V9LHsiaWQiOiIwMzY2ODliZi00MjM3LTRiNWItYmUyOS01ODRhOTE4MDMyNDEiLCJuYW1lIjoiY293IG1pbGsiLCJ0eXBlIjoiZGFpcnkiLCJpc19hbGxlcmdlbiI6dHJ1ZSwiaXNfZGVjbGFyYWJsZSI6dHJ1ZX1dLCJmb3JtcyI6W3siaWQiOiJ3aGV5IiwibWF0dGVyX3N0YXRlIjoibGlxdWlkIn0seyJpZCI6IndwYyIsIm1hdHRlcl9zdGF0ZSI6InBvd2RlciJ9LHsiaWQiOiJjdXJkIiwibWF0dGVyX3N0YXRlIjoic2VtaV9zb2xpZCJ9LHsiaWQiOiJnaGVlIiwibWF0dGVyX3N0YXRlIjoic2VtaV9zb2xpZCJ9LHsiaWQiOiJraG9hIiwibWF0dGVyX3N0YXRlIjoic2VtaV9zb2xpZCJ9LHsiaWQiOiJjcmVhbSIsIm1hdHRlcl9zdGF0ZSI6InZpc2NvdXMifSx7ImlkIjoiYnV0dGVyIiwibWF0dGVyX3N0YXRlIjoic2VtaV9zb2xpZCJ9LHsiaWQiOiJjaGVlc2UiLCJtYXR0ZXJfc3RhdGUiOiJzZW1pX3NvbGlkIn0seyJpZCI6InBhbmVlciIsIm1hdHRlcl9zdGF0ZSI6InNlbWlfc29saWQifSx7ImlkIjoieW9naHVydCIsIm1hdHRlcl9zdGF0ZSI6InNlbWlfc29saWQifSx7ImlkIjoic291cl9jcmVhbSIsIm1hdHRlcl9zdGF0ZSI6InZpc2NvdXMifSx7ImlkIjoic21wX3Bvd2RlciIsIm1hdHRlcl9zdGF0ZSI6InBvd2RlciJ9LHsiaWQiOiJtaWxrX3Bvd2RlciIsIm1hdHRlcl9zdGF0ZSI6InBvd2RlciJ9LHsiaWQiOiJjYXNlaW4iLCJtYXR0ZXJfc3RhdGUiOiJzZW1pX3NvbGlkIn0seyJpZCI6InRvbmVkX21pbGsiLCJtYXR0ZXJfc3RhdGUiOiJsaXF1aWQifSx7ImlkIjoic3dlZXRfd2hleSIsIm1hdHRlcl9zdGF0ZSI6ImxpcXVpZCJ9LHsiaWQiOiJ3aGl0ZV9idXR0ZXIiLCJtYXR0ZXJfc3RhdGUiOiJzZW1pX3NvbGlkIn0seyJpZCI6Im1pbGtfcHJvdGVpbiIsIm1hdHRlcl9zdGF0ZSI6ImxpcXVpZCJ9LHsiaWQiOiJ3aGV5X3BlcHRpZGVzIiwibWF0dGVyX3N0YXRlIjoibGlxdWlkIn0seyJpZCI6ImNoZWVzZV9wb3dkZXIiLCJtYXR0ZXJfc3RhdGUiOiJwb3dkZXIifSx7ImlkIjoieW9ndXJ0X3Bvd2RlciIsIm1hdHRlcl9zdGF0ZSI6InBvd2RlciJ9LHsiaWQiOiJyZW5uZXRfY2FzZWluIiwibWF0dGVyX3N0YXRlIjoicG93ZGVyIn0seyJpZCI6ImN1bHR1cmVkX2NyZWFtIiwibWF0dGVyX3N0YXRlIjoidmlzY291cyJ9LHsiaWQiOiJkb3VibGVfdG9uZWRfbWlsayIsIm1hdHRlcl9zdGF0ZSI6ImxpcXVpZCJ9LHsiaWQiOiJwYXJ0bHlfc2tpbW1lZF9taWxrIiwibWF0dGVyX3N0YXRlIjoibGlxdWlkIn0seyJpZCI6ImNvd19taWxrIiwibWF0dGVyX3N0YXRlIjoibGlxdWlkIn0seyJpZCI6Im1pbGtfcHJvdGVpbl9jb25jZW50cmF0ZSIsIm1hdHRlcl9zdGF0ZSI6InBvd2RlciJ9LHsiaWQiOiJjYWxjaXVtX2Nhc2VpbmF0ZSIsIm1hdHRlcl9zdGF0ZSI6InBvd2RlciJ9LHsiaWQiOiJzd2VldF9jcmVhbV9wb3dkZXIiLCJtYXR0ZXJfc3RhdGUiOiJwb3dkZXIifSx7ImlkIjoid2hleV9wZXJtZWF0ZV9wb3dkZXIiLCJtYXR0ZXJfc3RhdGUiOiJwb3dkZXIifSx7ImlkIjoiYnVmZmFsb19taWxrIiwibWF0dGVyX3N0YXRlIjoibGlxdWlkIn0seyJpZCI6InJhd19taWxrIiwibWF0dGVyX3N0YXRlIjoibGlxdWlkIn0seyJpZCI6IndoZXlfcHJvdGVpbl9pc29sYXRlIiwibWF0dGVyX3N0YXRlIjoicG93ZGVyIn0seyJpZCI6InNvZGl1bV9jYXNlaW5hdGUiLCJtYXR0ZXJfc3RhdGUiOiJwb3dkZXIifV0sInJlbGF0aW9ucyI6W3siaWQiOiI4MmNiZjE5Ni1kZjljLTQyOWItOGMwYy03ZDRjNzIxODViZGMiLCJ0eXBlIjoiRm9ybU9mIiwib3JpZ2luIjoiYzEzODc3OGMtZmZkMS00NzRjLWE0YmEtZjE1NTg4ZDAzOGFiIiwiZm9ybSI6IndoZXkiLCJwcm9jZXNzaW5nX21ldGhvZHMiOlsiY29hZ3VsYXRpb24iXX0seyJpZCI6IjQ5NTM5OTdkLTg2MzUtNGJlYS1iZjIxLWNiYmQ0OTA2ZTdiMSIsInR5cGUiOiJGb3JtT2YiLCJvcmlnaW4iOiJ3aGV5IiwiZm9ybSI6IndwYyIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJ1bHRyYWZpbHRyYXRpb24iLCJkcnlpbmctc3ByYXkiXX0seyJpZCI6ImU3NDdjZTViLTFhM2MtNDg2Yi05ZWNmLTZkY2RiM2M1NWEyYiIsInR5cGUiOiJGb3JtT2YiLCJvcmlnaW4iOiJjMTM4Nzc4Yy1mZmQxLTQ3NGMtYTRiYS1mMTU1ODhkMDM4YWIiLCJmb3JtIjoiY3VyZCIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJmZXJtZW50YXRpb24iLCJjb2FndWxhdGlvbiJdfSx7ImlkIjoiNTlkNGI3YzQtMjczZi00NmU1LWI1YjUtYjMxNTc4OTdiZTZlIiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6ImJ1dHRlciIsImZvcm0iOiJnaGVlIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbImNsYXJpZmljYXRpb24iXX0seyJpZCI6Ijc3YzUxOWIzLTc4ZjQtNDRmOC04ZjE5LTUyYTJjYzYzOTUwNiIsInR5cGUiOiJGb3JtT2YiLCJvcmlnaW4iOiJjMTM4Nzc4Yy1mZmQxLTQ3NGMtYTRiYS1mMTU1ODhkMDM4YWIiLCJmb3JtIjoia2hvYSIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJldmFwb3JhdGlvbiJdfSx7ImlkIjoiNmJlMzMzZTctOGFkMC00MzJiLWExMTctYTljZDNlMjcyNjgzIiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6ImMxMzg3NzhjLWZmZDEtNDc0Yy1hNGJhLWYxNTU4OGQwMzhhYiIsImZvcm0iOiJjcmVhbSIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJjZW50cmlmdWdhdGlvbiJdfSx7ImlkIjoiNThjY2Y1ZTAtYzcyNC00NWRiLWFkMjUtMWVkNGEzZWYwNDU2IiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6ImNyZWFtIiwiZm9ybSI6ImJ1dHRlciIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJjaHVybmluZyJdfSx7ImlkIjoiNzFkYjRmZmEtY2Q1NC00Y2Y2LThmODItNGYwMmQzMjg3Y2E2IiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6ImMxMzg3NzhjLWZmZDEtNDc0Yy1hNGJhLWYxNTU4OGQwMzhhYiIsImZvcm0iOiJjaGVlc2UiLCJwcm9jZXNzaW5nX21ldGhvZHMiOlsiY29hZ3VsYXRpb24iLCJmZXJtZW50YXRpb24iXX0seyJpZCI6IjcxMjljODM1LWVjZDgtNDJhMS1hMTE1LTg1MTM1Yjg5YzFjYiIsInR5cGUiOiJGb3JtT2YiLCJvcmlnaW4iOiJjMTM4Nzc4Yy1mZmQxLTQ3NGMtYTRiYS1mMTU1ODhkMDM4YWIiLCJmb3JtIjoicGFuZWVyIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbImNvYWd1bGF0aW9uIl19LHsiaWQiOiJkMDJhMGRlYi05MGY2LTRlZTEtODgyNy0yYjYyOGQ4YzhkZTQiLCJ0eXBlIjoiRm9ybU9mIiwib3JpZ2luIjoiYzEzODc3OGMtZmZkMS00NzRjLWE0YmEtZjE1NTg4ZDAzOGFiIiwiZm9ybSI6InlvZ2h1cnQiLCJwcm9jZXNzaW5nX21ldGhvZHMiOlsiZmVybWVudGF0aW9uIl19LHsiaWQiOiJkNDM5NzEyZS05ZDIyLTQwOGYtYWE5NC1hNTk3YmJjYjQ2MzciLCJ0eXBlIjoiRm9ybU9mIiwib3JpZ2luIjoiY3JlYW0iLCJmb3JtIjoic291cl9jcmVhbSIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJjZW50cmlmdWdhdGlvbiIsImZlcm1lbnRhdGlvbiJdfSx7ImlkIjoiMmMxNzUyZDItYjUzZC00YmU2LWE2NzYtNTk4NzA3MWRkOWY5IiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6ImMxMzg3NzhjLWZmZDEtNDc0Yy1hNGJhLWYxNTU4OGQwMzhhYiIsImZvcm0iOiJzbXBfcG93ZGVyIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbInNraW1taW5nIiwiZHJ5aW5nLXNwcmF5Il19LHsiaWQiOiIyYWRjNmNmYS0xYzgwLTRlNWUtOTNkYi1hYTE0OGNhZmYwYTIiLCJ0eXBlIjoiRm9ybU9mIiwib3JpZ2luIjoiYzEzODc3OGMtZmZkMS00NzRjLWE0YmEtZjE1NTg4ZDAzOGFiIiwiZm9ybSI6Im1pbGtfcG93ZGVyIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbImRyeWluZy1zcHJheSJdfSx7ImlkIjoiMzE2ZGVlYmItOWUyZC00ODZhLWJjZDctZmQ4NGQ4OTk4ODE4IiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6ImMxMzg3NzhjLWZmZDEtNDc0Yy1hNGJhLWYxNTU4OGQwMzhhYiIsImZvcm0iOiJjYXNlaW4iLCJwcm9jZXNzaW5nX21ldGhvZHMiOlsiY29hZ3VsYXRpb24iXX0seyJpZCI6IjE5Y2FlZGMzLTExYzUtNDdkMC1hNWRhLWI1NGI1Zjk0NzZjYiIsInR5cGUiOiJGb3JtT2YiLCJvcmlnaW4iOiJjMTM4Nzc4Yy1mZmQxLTQ3NGMtYTRiYS1mMTU1ODhkMDM4YWIiLCJmb3JtIjoidG9uZWRfbWlsayIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJzdGFuZGFyZGl6YXRpb24iXX0seyJpZCI6ImEwNGE2NmUyLWVjMzgtNDM4ZC1hODEzLWQ0MzFmNDFkMmI5OCIsInR5cGUiOiJGb3JtT2YiLCJvcmlnaW4iOiJ3aGV5IiwiZm9ybSI6InN3ZWV0X3doZXkiLCJwcm9jZXNzaW5nX21ldGhvZHMiOlsiY29hZ3VsYXRpb24iXX0seyJpZCI6IjJmNDE0YjQ2LWVhZmYtNGNjMC1iMDM1LTI2MDRiMTBlYzk3YiIsInR5cGUiOiJGb3JtT2YiLCJvcmlnaW4iOiJjcmVhbSIsImZvcm0iOiJ3aGl0ZV9idXR0ZXIiLCJwcm9jZXNzaW5nX21ldGhvZHMiOlsiY2h1cm5pbmciXX0seyJpZCI6ImRjMmNiNjM3LTJmMjItNGQ2YS1hYmVkLTJhYTJmNTQ2MGZlMCIsInR5cGUiOiJGb3JtT2YiLCJvcmlnaW4iOiJjMTM4Nzc4Yy1mZmQxLTQ3NGMtYTRiYS1mMTU1ODhkMDM4YWIiLCJmb3JtIjoibWlsa19wcm90ZWluIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbImZpbHRyYXRpb24iXX0seyJpZCI6IjhmZDAwYWY0LWE1NmYtNDE1Yy04MjU4LWRkZmU0ZTU4MjkyYSIsInR5cGUiOiJGb3JtT2YiLCJvcmlnaW4iOiJ3aGV5IiwiZm9ybSI6IndoZXlfcGVwdGlkZXMiLCJwcm9jZXNzaW5nX21ldGhvZHMiOlsiaHlkcm9seXNpcyJdfSx7ImlkIjoiYzg1MGZmM2YtN2VjYS00NmY3LWJkZDItMWIyMWJjYzAzOGU1IiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6ImNoZWVzZSIsImZvcm0iOiJjaGVlc2VfcG93ZGVyIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbImRyeWluZy1zcHJheSJdfSx7ImlkIjoiOTU1YjlkNmItMWU1Yi00NzE1LTk2M2EtMThhYmI3ZDg5NzkwIiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6InlvZ2h1cnQiLCJmb3JtIjoieW9ndXJ0X3Bvd2RlciIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJkcnlpbmctc3ByYXkiXX0seyJpZCI6IjQ5ZTViOGZiLWFiZTgtNDFhMy05NmJhLWJjYzc4NDU3ZjFiMSIsInR5cGUiOiJGb3JtT2YiLCJvcmlnaW4iOiJjYXNlaW4iLCJmb3JtIjoicmVubmV0X2Nhc2VpbiIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJkcnlpbmctc3ByYXkiXX0seyJpZCI6IjA0YmUzYzljLTVmYmItNDQyYi1iZmU5LTI2ODFkOGFmYjI1ZCIsInR5cGUiOiJGb3JtT2YiLCJvcmlnaW4iOiJjcmVhbSIsImZvcm0iOiJjdWx0dXJlZF9jcmVhbSIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJmZXJtZW50YXRpb24iXX0seyJpZCI6IjIxOTJkMWZlLWU2OTQtNDIwYy04YjBjLTE0MWE3M2FiZTUwMSIsInR5cGUiOiJGb3JtT2YiLCJvcmlnaW4iOiJjMTM4Nzc4Yy1mZmQxLTQ3NGMtYTRiYS1mMTU1ODhkMDM4YWIiLCJmb3JtIjoiZG91YmxlX3RvbmVkX21pbGsiLCJwcm9jZXNzaW5nX21ldGhvZHMiOlsic3RhbmRhcmRpemF0aW9uIl19LHsiaWQiOiI0M2Y4MDRiYy0yZGZhLTQ0YmYtYWUwZS0wMWJiZDhhZjRkYTQiLCJ0eXBlIjoiRm9ybU9mIiwib3JpZ2luIjoiYzEzODc3OGMtZmZkMS00NzRjLWE0YmEtZjE1NTg4ZDAzOGFiIiwiZm9ybSI6InBhcnRseV9za2ltbWVkX21pbGsiLCJwcm9jZXNzaW5nX21ldGhvZHMiOlsic2tpbW1pbmciXX0seyJpZCI6ImU0Yzg3MWI2LWE5ZDMtNDRmNC1iYmY1LTJhZmE1NjMxZWY2MyIsInR5cGUiOiJWYXJpZXR5T2YiLCJiYXNlIjoiYzEzODc3OGMtZmZkMS00NzRjLWE0YmEtZjE1NTg4ZDAzOGFiIiwidmFyaWV0eSI6ImNvd19taWxrIn0seyJpZCI6ImVmYzJhYWUyLWZjZWYtNDZhZi05NTQ0LTE0OWQyZmZjMmExYSIsInR5cGUiOiJGb3JtT2YiLCJvcmlnaW4iOiJtaWxrX3Byb3RlaW4iLCJmb3JtIjoibWlsa19wcm90ZWluX2NvbmNlbnRyYXRlIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbImRyeWluZy1zcHJheSJdfSx7ImlkIjoiMzY3YWZhYWMtNzU4OC00NGMxLTg4ODYtZDgyMTJmOGQwYWFlIiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6ImNhc2VpbiIsImZvcm0iOiJjYWxjaXVtX2Nhc2VpbmF0ZSIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJuZXV0cmFsaXphdGlvbiIsImRyeWluZy1zcHJheSJdfSx7ImlkIjoiMTEwZDI4YTItODRiZS00M2Y3LWE3ZWUtZjRmMDNlMjVlOGJlIiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6ImNyZWFtIiwiZm9ybSI6InN3ZWV0X2NyZWFtX3Bvd2RlciIsInByb2Nlc3NpbmdfbWV0aG9kcyI6WyJkcnlpbmctc3ByYXkiXX0seyJpZCI6ImEzNDQwZjIyLTkxNmQtNGE3OS05MmIxLTM1ZGYwZTdjMWEyNyIsInR5cGUiOiJGb3JtT2YiLCJvcmlnaW4iOiJ3aGV5IiwiZm9ybSI6IndoZXlfcGVybWVhdGVfcG93ZGVyIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbInVsdHJhZmlsdHJhdGlvbiIsImRyeWluZy1zcHJheSJdfSx7ImlkIjoiNmExN2UzZmEtNTM4NS00NmMyLTg3NjYtYTkwNWI2ODk3NDNkIiwidHlwZSI6IlZhcmlldHlPZiIsImJhc2UiOiJjMTM4Nzc4Yy1mZmQxLTQ3NGMtYTRiYS1mMTU1ODhkMDM4YWIiLCJ2YXJpZXR5IjoiYnVmZmFsb19taWxrIn0seyJpZCI6ImYzNjJlNjM4LWI2MzctNDIwMi05MzQ3LWUxYWM4ZmMyNGQ5ZSIsInR5cGUiOiJWYXJpZXR5T2YiLCJiYXNlIjoiYzEzODc3OGMtZmZkMS00NzRjLWE0YmEtZjE1NTg4ZDAzOGFiIiwidmFyaWV0eSI6InJhd19taWxrIn0seyJpZCI6IjhiMzZjMzU0LTQ2MjAtNDNiYi1iYmFlLWZkN2VlZDQwY2I0ZCIsInR5cGUiOiJGb3JtT2YiLCJvcmlnaW4iOiJ3aGV5IiwiZm9ybSI6IndoZXlfcHJvdGVpbl9pc29sYXRlIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbInVsdHJhZmlsdHJhdGlvbiIsImRyeWluZy1zcHJheSJdfSx7ImlkIjoiMTcyYzkyY2EtYTI2NC00Mjc3LTk0MjEtMzkyYTNiODM3N2RmIiwidHlwZSI6IkZvcm1PZiIsIm9yaWdpbiI6ImNhc2VpbiIsImZvcm0iOiJzb2RpdW1fY2FzZWluYXRlIiwicHJvY2Vzc2luZ19tZXRob2RzIjpbIm5ldXRyYWxpemF0aW9uIiwiZHJ5aW5nLXNwcmF5Il19XSwiY3VzdG9tTWV0aG9kcyI6WyJjZW50cmlmdWdhdGlvbiIsInN0YW5kYXJkaXphdGlvbiIsImZpbHRyYXRpb24iLCJoeWRyb2x5c2lzIiwibmV1dHJhbGl6YXRpb24iXSwiY3VzdG9tTWF0dGVyU3RhdGVzIjpbInZpc2NvdXMiXSwiY3VzdG9tU291cmNlVHlwZXMiOltdfQ==

# ── New enum values — add these to enum_requests.md ──────────────────
# NEW  processing_method: "centrifugation"
# NEW  processing_method: "standardization"
# NEW  processing_method: "filtration"
# NEW  processing_method: "hydrolysis"
# NEW  processing_method: "neutralization"
# NEW  matter_state: "viscous"
# ─────────────────────────────────────────────────────────────────────

from index import Database, Source, IngredientForm, FormOf, VarietyOf

db = Database()

milk = db.add(Source(
    name="milk",
    type="dairy",
    is_allergen=True,
    is_declarable=True
))
db.relate(FormOf(origin=milk, form=whey, processing_method=["coagulation"]))
db.relate(FormOf(origin=milk, form=curd, processing_method=["fermentation", "coagulation"]))
db.relate(FormOf(origin=milk, form=khoa, processing_method=["evaporation"]))
db.relate(FormOf(origin=milk, form=cream, processing_method=["centrifugation"]))  # NEW processing_method
db.relate(FormOf(origin=milk, form=cheese, processing_method=["coagulation", "fermentation"]))
db.relate(FormOf(origin=milk, form=paneer, processing_method=["coagulation"]))
db.relate(FormOf(origin=milk, form=yoghurt, processing_method=["fermentation"]))
db.relate(FormOf(origin=milk, form=smp_powder, processing_method=["skimming", "drying-spray"]))
db.relate(FormOf(origin=milk, form=milk_powder, processing_method=["drying-spray"]))
db.relate(FormOf(origin=milk, form=casein, processing_method=["coagulation"]))
db.relate(FormOf(origin=milk, form=toned_milk, processing_method=["standardization"]))  # NEW processing_method
db.relate(FormOf(origin=milk, form=milk_protein, processing_method=["filtration"]))  # NEW processing_method
db.relate(FormOf(origin=milk, form=double_toned_milk, processing_method=["standardization"]))  # NEW processing_method
db.relate(FormOf(origin=milk, form=partly_skimmed_milk, processing_method=["skimming"]))

streptococcus_thermophilus = db.add(Source(
    name="streptococcus thermophilus",
    type="microbial",
    is_allergen=False,
    is_declarable=False
))

lactobacillus_acidophilus = db.add(Source(
    name="lactobacillus acidophilus",
    type="microbial",
    is_allergen=False,
    is_declarable=False
))

lactobacillus_delbrueckii_subsp_bulgaricus = db.add(Source(
    name="lactobacillus delbrueckii subsp. bulgaricus",
    type="microbial",
    is_allergen=False,
    is_declarable=False
))

limosilactobacillus_reuteri = db.add(Source(
    name="limosilactobacillus reuteri",
    type="microbial",
    is_allergen=False,
    is_declarable=False
))

bifidobacterium_animalis_subsp_lactis = db.add(Source(
    name="bifidobacterium animalis subsp. lactis",
    type="microbial",
    is_allergen=False,
    is_declarable=False
))

cow_milk = db.add(Source(
    name="cow milk",
    type="dairy",
    is_allergen=True,
    is_declarable=True
))

whey = db.add(IngredientForm(id="whey", matter_state="liquid"))
db.relate(FormOf(origin=whey, form=wpc, processing_method=["ultrafiltration", "drying-spray"]))
db.relate(FormOf(origin=whey, form=sweet_whey, processing_method=["coagulation"]))
db.relate(FormOf(origin=whey, form=whey_peptides, processing_method=["hydrolysis"]))  # NEW processing_method
db.relate(FormOf(origin=whey, form=whey_permeate_powder, processing_method=["ultrafiltration", "drying-spray"]))
db.relate(FormOf(origin=whey, form=whey_protein_isolate, processing_method=["ultrafiltration", "drying-spray"]))

wpc = db.add(IngredientForm(id="wpc", matter_state="powder"))

curd = db.add(IngredientForm(id="curd", matter_state="semi_solid"))

cream = db.add(IngredientForm(id="cream", matter_state="viscous"))  # NEW matter_state
db.relate(FormOf(origin=cream, form=butter, processing_method=["churning"]))
db.relate(FormOf(origin=cream, form=sour_cream, processing_method=["centrifugation", "fermentation"]))  # NEW processing_method
db.relate(FormOf(origin=cream, form=white_butter, processing_method=["churning"]))
db.relate(FormOf(origin=cream, form=cultured_cream, processing_method=["fermentation"]))
db.relate(FormOf(origin=cream, form=sweet_cream_powder, processing_method=["drying-spray"]))

butter = db.add(IngredientForm(id="butter", matter_state="semi_solid"))
db.relate(FormOf(origin=butter, form=ghee, processing_method=["clarification"]))

ghee = db.add(IngredientForm(id="ghee", matter_state="semi_solid"))

khoa = db.add(IngredientForm(id="khoa", matter_state="semi_solid"))

cheese = db.add(IngredientForm(id="cheese", matter_state="semi_solid"))
db.relate(FormOf(origin=cheese, form=cheese_powder, processing_method=["drying-spray"]))

paneer = db.add(IngredientForm(id="paneer", matter_state="semi_solid"))

yoghurt = db.add(IngredientForm(id="yoghurt", matter_state="semi_solid"))
db.relate(FormOf(origin=yoghurt, form=yogurt_powder, processing_method=["drying-spray"]))

sour_cream = db.add(IngredientForm(id="sour_cream", matter_state="viscous"))  # NEW matter_state

smp_powder = db.add(IngredientForm(id="smp_powder", matter_state="powder"))

milk_powder = db.add(IngredientForm(id="milk_powder", matter_state="powder"))

casein = db.add(IngredientForm(id="casein", matter_state="semi_solid"))
db.relate(FormOf(origin=casein, form=rennet_casein, processing_method=["drying-spray"]))
db.relate(FormOf(origin=casein, form=calcium_caseinate, processing_method=["neutralization", "drying-spray"]))  # NEW processing_method
db.relate(FormOf(origin=casein, form=sodium_caseinate, processing_method=["neutralization", "drying-spray"]))  # NEW processing_method

toned_milk = db.add(IngredientForm(id="toned_milk", matter_state="liquid"))

sweet_whey = db.add(IngredientForm(id="sweet_whey", matter_state="liquid"))

white_butter = db.add(IngredientForm(id="white_butter", matter_state="semi_solid"))

milk_protein = db.add(IngredientForm(id="milk_protein", matter_state="liquid"))
db.relate(FormOf(origin=milk_protein, form=milk_protein_concentrate, processing_method=["drying-spray"]))

whey_peptides = db.add(IngredientForm(id="whey_peptides", matter_state="liquid"))

cheese_powder = db.add(IngredientForm(id="cheese_powder", matter_state="powder"))

yogurt_powder = db.add(IngredientForm(id="yogurt_powder", matter_state="powder"))

rennet_casein = db.add(IngredientForm(id="rennet_casein", matter_state="powder"))

cultured_cream = db.add(IngredientForm(id="cultured_cream", matter_state="viscous"))  # NEW matter_state

double_toned_milk = db.add(IngredientForm(id="double_toned_milk", matter_state="liquid"))

partly_skimmed_milk = db.add(IngredientForm(id="partly_skimmed_milk", matter_state="liquid"))

cow_milk = db.add(IngredientForm(id="cow_milk", matter_state="liquid"))
db.relate(VarietyOf(base=milk, variety=cow_milk))

milk_protein_concentrate = db.add(IngredientForm(id="milk_protein_concentrate", matter_state="powder"))

calcium_caseinate = db.add(IngredientForm(id="calcium_caseinate", matter_state="powder"))

sweet_cream_powder = db.add(IngredientForm(id="sweet_cream_powder", matter_state="powder"))

whey_permeate_powder = db.add(IngredientForm(id="whey_permeate_powder", matter_state="powder"))

buffalo_milk = db.add(IngredientForm(id="buffalo_milk", matter_state="liquid"))
db.relate(VarietyOf(base=milk, variety=buffalo_milk))

raw_milk = db.add(IngredientForm(id="raw_milk", matter_state="liquid"))
db.relate(VarietyOf(base=milk, variety=raw_milk))

whey_protein_isolate = db.add(IngredientForm(id="whey_protein_isolate", matter_state="powder"))

sodium_caseinate = db.add(IngredientForm(id="sodium_caseinate", matter_state="powder"))

print(db)